# Generated by Django 4.0.5 on 2022-06-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelinePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TimelinePage name')),
                ('about', models.TextField(verbose_name='TimelinePage about')),
                ('year', models.IntegerField(verbose_name='TimelinePage year')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
            },
        ),
    ]
