# Generated by Django 4.0.5 on 2022-06-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_timelinepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='TestPage title')),
                ('about', models.TextField(verbose_name='TestPage about')),
                ('name', models.TextField(verbose_name='TestPage name')),
                ('surname', models.TextField(verbose_name='TestPage surname')),
                ('year', models.CharField(max_length=30, verbose_name='TimelinePage year')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.AlterField(
            model_name='timelinepage',
            name='year',
            field=models.CharField(max_length=30, verbose_name='TimelinePage year'),
        ),
    ]
