# Generated by Django 4.0.5 on 2022-06-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_testpage_alter_timelinepage_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpage',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='TestPage img1'),
        ),
    ]
