# Generated by Django 4.0.5 on 2022-06-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testpage_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpage',
            name='year',
        ),
    ]
